name: "User Story"
description: "Luo uusi User Story"
title: "Käyttäjä "
type: "User Story"
body:
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Hyväksymäkriteerit
      placeholder: |
        Esim.
        - [ ] Huoneen väri määräytyy vapaiden paikkojen mukaan
        - [ ] Jos käyttäjä ei ole kirjautunut sisään, ohjataan yliopiston kirjautumissivulle.
  - type: textarea
    id: notes
    attributes:
      label: Muuta huomioitavaa
      placeholder: |
        Esim. Varausaste ilmoitetaan joko muodossa varatut/kokonaismäärä tai vapaat/kokonaismäärä.
