name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  release:

jobs:
  ci-frontend:
    name: CI / Frontend
    uses: ./.github/workflows/ci-frontend.yaml

  ci-backend:
    name: CI / Backend
    uses: ./.github/workflows/ci-backend.yaml

  ci-app:
    name: CI / App
    uses: ./.github/workflows/ci-app.yaml

  cd-build-and-push-staging:
    name: CD / Build and Push (Staging)
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ci-frontend, ci-backend, ci-app]
    uses: ./.github/workflows/cd-build-and-push.yaml
    secrets: inherit
    with:
      target: staging

  cd-build-and-push-prod:
    name: CD / Build and Push (Production)
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [ci-frontend, ci-backend, ci-app]
    uses: ./.github/workflows/cd-build-and-push.yaml
    secrets: inherit
    with:
      target: prod
