name: "e2e pipeline"

on:
  workflow_call:

jobs:
  test: #also builds
    runs-on: ubuntu-24.04
    services:
        postgres:
            image: postgres:alpine
            env:
                POSTGRES_PASSWORD: postgres
                POSTGRES_USER: postgres
                POSTGRES_DB: test_db
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
            - 5432:5432
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '25'
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json
    - name: Install dependencies
      run: npm run install:all && npm install
    - name: Build
      run: npm run build:backend && npm run build:frontend
    - name: Install playwright
      run: npx playwright install
    - name: start backend
      run: npm run dev:backend &
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        PORT: 3000
    - name: start frontend
      run: npm run dev:frontend &
    - name: Run e2e-tests
      run: npm run test:e2e


